[behavex]
parallel_processes = 4
show_progress = true
features_path=source/features

[behave]
paths = source/features
steps_dir = source/features/steps

# Allure report configuration
format = allure_behave.formatter:AllureFormatter
outfiles = allure-results